# Generated by Django 5.2 on 2025-09-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='is_settled',
        ),
        migrations.AddField(
        model_name='debt',
            name='date_repaid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='is_repaid',
            field=models.BooleanField(default=False),
        ),
    ]
